/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "IwDebug.h"
#include "CGPollfish_autodefs.h"
#include "s3eEdk.h"
#include "CGPollfish.h"
//Declarations of Init and Term functions
extern s3eResult CGPollfishInit();
extern void CGPollfishTerminate();


// On platforms that use a seperate UI/OS thread we can autowrap functions
// here.   Note that we can't use the S3E_USE_OS_THREAD define since this
// code is oftern build standalone, outside the main loader build.
#if defined I3D_OS_IPHONE || defined I3D_OS_OSX || defined I3D_OS_LINUX || defined I3D_OS_WINDOWS

static void PollFishInit_wrap(const char* apiKey, CGPollFishPosition position, int padding, const char* userId)
{
    IwTrace(CGPOLLFISH_VERBOSE, ("calling CGPollfish func on main thread: PollFishInit"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)PollFishInit, 4, apiKey, position, padding, userId);
}

static void PollFishHide_wrap()
{
    IwTrace(CGPOLLFISH_VERBOSE, ("calling CGPollfish func on main thread: PollFishHide"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)PollFishHide, 0);
}

static void PollFishShow_wrap()
{
    IwTrace(CGPOLLFISH_VERBOSE, ("calling CGPollfish func on main thread: PollFishShow"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)PollFishShow, 0);
}

#define PollFishInit PollFishInit_wrap

#define PollFishHide PollFishHide_wrap

#define PollFishShow PollFishShow_wrap


#endif

s3eResult CGPollfishRegister(CGPollfishCallback cbid, s3eCallback fn, void* pData)
{
    return s3eEdkCallbacksRegister(S3E_EXT_CGPOLLFISH_HASH, CGPOLLFISH_CALLBACK_MAX, cbid, fn, pData, 0);
};

s3eResult CGPollfishUnRegister(CGPollfishCallback cbid, s3eCallback fn)
{
    return s3eEdkCallbacksUnRegister(S3E_EXT_CGPOLLFISH_HASH, CGPOLLFISH_CALLBACK_MAX, cbid, fn);
}

void CGPollfishRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[5];
    funcPtrs[0] = (void*)CGPollfishRegister;
    funcPtrs[1] = (void*)CGPollfishUnRegister;
    funcPtrs[2] = (void*)PollFishInit;
    funcPtrs[3] = (void*)PollFishHide;
    funcPtrs[4] = (void*)PollFishShow;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[5] = { 0 };

    /*
     * Register the extension
     */
s3eEdkRegister("CGPollfish", funcPtrs, sizeof(funcPtrs), flags, CGPollfishInit, CGPollfishTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int CGPollfishStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&CGPollfishRegisterExt;
    return 0;
}

int g_CGPollfishVal = CGPollfishStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    CGPollfishRegisterExt();
}
#endif

#endif
