/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef CGPOLLFISH_AUTODEFS_H
#define CGPOLLFISH_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_CGPOLLFISH_NAME "CGPollfish"
#define S3E_EXT_CGPOLLFISH_HASH 0x64ec2770

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("CGPollfish", 5)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !CGPOLLFISH_AUTODEFS_H */
