/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef  s3eResult(*CGPollfishRegister_t)(CGPollfishCallback cbid, s3eCallback fn, void* userData);
typedef  s3eResult(*CGPollfishUnRegister_t)(CGPollfishCallback cbid, s3eCallback fn);
typedef       void(*PollFishInit_t)(const char* apiKey, CGPollFishPosition position, int padding, const char* userId);
typedef       void(*PollFishHide_t)();
typedef       void(*PollFishShow_t)();

/**
 * struct that gets filled in by CGPollfishRegister
 */
typedef struct CGPollfishFuncs
{
    CGPollfishRegister_t m_CGPollfishRegister;
    CGPollfishUnRegister_t m_CGPollfishUnRegister;
    PollFishInit_t m_PollFishInit;
    PollFishHide_t m_PollFishHide;
    PollFishShow_t m_PollFishShow;
} CGPollfishFuncs;
