/*
 * (C) 2001-2012 Marmalade. All Rights Reserved.
 *
 * This document is protected by copyright, and contains information
 * proprietary to Marmalade.
 *
 * This file consists of source code released by Marmalade under
 * the terms of the accompanying End User License Agreement (EULA).
 * Please do not use this program/source code before you have read the
 * EULA and have agreed to be bound by its terms.
 */
/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3E_EXT_CGPOLLFISH_H
#define S3E_EXT_CGPOLLFISH_H

#include <s3eTypes.h>


typedef enum CGPollfishCallback
{
    CGPOLLFISH_CALLBACK_RECEIVED = 0,
    CGPOLLFISH_CALLBACK_NOTAVAILABLE = 1,
    CGPOLLFISH_CALLBACK_COMPLETED = 2,
    CGPOLLFISH_CALLBACK_OPENED = 3,
    CGPOLLFISH_CALLBACK_CLOSED = 4,
    CGPOLLFISH_CALLBACK_NOTELIGIBLE = 5,
    CGPOLLFISH_CALLBACK_MAX
} CGPollfishCallback;


typedef enum CGPollFishPosition
{
    POSITION_TOP_LEFT   = 1,
    POSITION_BOTTOM_LEFT = 2,
    POSITION_MIDDLE_LEFT = 3,
    POSITION_TOP_RIGHT = 4,
    POSITION_BOTTOM_RIGHT = 5,
    POSITION_MIDDLE_RIGHT = 6
} CGPollFishPosition;
// \cond HIDDEN_DEFINES
S3E_BEGIN_C_DECL
// \endcond

/**
 * Returns S3E_TRUE if the CGPollfish extension is available.
 */
s3eBool CGPollfishAvailable();

/**
 * Registers a callback to be called for an operating system event.
 *
 * The available callback types are listed in @ref CGPollfishCallback.
 * @param cbid ID of the event for which to register.
 * @param fn callback function.
 * @param userdata Value to pass to the @e userdata parameter of @e NotifyFunc.
 * @return
 *  - @ref S3E_RESULT_SUCCESS if no error occurred.
 *  - @ref S3E_RESULT_ERROR if the operation failed.\n
 *
 * @see CGPollfishUnRegister
 * @note For more information on the system data passed as a parameter to the callback
 * registered using this function, see the @ref CGPollfishCallback enum.
 */
s3eResult CGPollfishRegister(CGPollfishCallback cbid, s3eCallback fn, void* userData);

/**
 * Unregister a callback for a given event.
 * @param cbid ID of the callback to unregister.
 * @param fn Callback Function.
 * @return
 * - @ref S3E_RESULT_SUCCESS if no error occurred.
 * - @ref S3E_RESULT_ERROR if the operation failed.\n
 * @note For more information on the systemData passed as a parameter to the callback
 * registered using this function, see the CGPollfishCallback enum.
 * @note It is not necessary to define a return value for any registered callback.
 * @see CGPollfishRegister
 */
s3eResult CGPollfishUnRegister(CGPollfishCallback cbid, s3eCallback fn);

void PollFishInit(const char* apiKey, CGPollFishPosition position, int padding, const char* userId);

void PollFishHide();

void PollFishShow();

// \cond HIDDEN_DEFINES
S3E_END_C_DECL
// \endcond

#endif /* !S3E_EXT_CGPOLLFISH_H */
